name: Continuous Integration

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # weekly
  workflow_dispatch:

jobs:
  ok:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: All Tests Passed
    needs: [test, memcheck]
    steps:
      - run: '[[ "${{ needs.test.result }}" == "success" && "${{ needs.memcheck.result }}" == "success" ]]'
  test:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        ruby: [3.1, 3.2, 3.3, head]
    continue-on-error: ${{ matrix.ruby == 'head' }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: make test
  memcheck:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: "memcheck"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "head"
          bundler-cache: true
      - name: Install dependencies
        run: sudo apt-get install -yqq valgrind
      - run: make memcheck
